name: dMC-Juniata-hydroDL2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.11.17=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.44.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=h59595ed_2
  - openssl=3.1.4=hd590300_0
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.11.6=hab00c5b_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.41.3=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.0.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - comm==0.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.0.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - fonttools==4.45.0
      - fqdn==1.5.1
      - fsspec==2023.10.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.3
      - hydra-core==1.3.2
      - idna==3.4
      - injector==0.21.0
      - ipykernel==6.27.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.11.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pillow==9.3.0
      - platformdirs==4.0.0
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - protobuf==4.23.4
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.31.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.13.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - torch==2.1.1+cpu
      - torchaudio==2.1.1+cpu
      - torchvision==0.16.1+cpu
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - triton==2.1.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
prefix: /home/tkb5476/.conda/envs/dMC-Juniata-hydroDL2
